### ISSUE TITLE
" go run example/main.go"  panic 

### ISSUE THREAD

**Issue by darrenli6** [hertz-contrib/casbin#5]
**Describe the bug**

" go run example/main.go"  panic 

**To Reproduce**

go run example/main.go

**Expected behavior**

run successfully

**Screenshots**
 
<img width="1382" alt="image" src="https://user-images.githubusercontent.com/23740296/218947755-a4380c90-64a7-40be-b0de-e9d9618dd960.png">

**Kitex version:**

main 

**Environment:**

GO111MODULE="on"
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/darren/Library/Caches/go-build"
GOENV="/Users/darren/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/darren/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/darren/go"
GOPRIVATE=""
GOPROXY="https://goproxy.io,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.19.2"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/darren/go/src/github.com/hertz-contrib/casbin/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/yw/k_z0z4393mz698xzl0df6_t80000gn/T/go-build3674836545=/tmp/go-build -gno-record-gcc-switches -fno-common"

**Additional context**

**Comment by L2ncE** [comment]
thx~ I will fix it.
